project:
  type: website

website:
  title: "Completitud Datos Elecciones Subnacionales 2026"
  navbar:
    left:
      - href: index.qmd
        text: Candidatos
      - href: partidos.qmd
        text: Partidos
      - href: surveys.qmd
        text: Encuestas
      - href: ranking.qmd
        text: Contribuidores

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



