name: Update Candidates

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-prices:
    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Configurar entorno e instalar dependencias
        run: |
          # 1. Usamos python3 explícitamente para crear el entorno virtual aislado
          python3 -m venv venv
          
          # 2. Activamos el entorno virtual
          source venv/bin/activate
          
          # 3. Magia: una vez activado el venv, el comando 'python' y 'pip' ya funcionan normalmente
          python -m pip install --upgrade pip
          pip install -r datos/requirements_collect.txt
          
          # Opcional: Ejecuta tu script de recolección de datos aquí mismo mientras el venv está activo
          # python main_collect.py

      - name: Run collection
        env:
          APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_KEY }}
          APPWRITE_URL: https://appwrite.sociest.org
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        run: python datos/collect.py
        continue-on-error: false

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update Candidates"
          git pull --rebase origin main

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
