name: Update Dashboard

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  update-prices:
    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Configurar entorno e instalar dependencias
        run: |
          python3 -m venv venv
          ./venv/bin/python -m pip install --upgrade pip
          ./venv/bin/pip install -r datos/requirements_collect.txt

      - name: Run collection
        env:
          APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_KEY }}
          APPWRITE_URL: https://appwrite.sociest.org
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        run: ./venv/bin/python datos/collect.py
        continue-on-error: false

      - name: Run collection
        env:
          APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_KEY }}
          APPWRITE_URL: https://appwrite.sociest.org
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        run: ./venv/bin/python datos/collect_partidos.py
        continue-on-error: false

      - name: Run collection
        env:
          APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_KEY }}
          APPWRITE_URL: https://appwrite.sociest.org
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        run: ./venv/bin/python datos/collect_surveys.py
        continue-on-error: false

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update Candidates"
          git pull --rebase origin main

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
